stages:
  - build
  - docker

variables:
  # Docker Hub image name
  DOCKER_IMAGE: "sureshvasantha/gitlab-frontend"
  NODE_VERSION: "22"

build-frontend:
  stage: build
  image: node:$NODE_VERSION
  script:
    - npm install
    - npx ng build --configuration production
  artifacts:
    paths:
      - "dist/"
  only:
    - gitlab-dev

docker-build-push:
  stage: docker
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$DOCKERHUB_PASS" | docker login -u $DOCKERHUB_USER --password-stdin
  script:
    - docker build -t $DOCKER_IMAGE:latest .
    - docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - gitlab-dev
